name: format
on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Add path for Poetry
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: install dependencies
        run: poetry add black isort
      - name: poetry run black format
        run: poetry run black .
      - name: poetry run isort format
        run: poetry run isort .
